<?php

namespace Database\Seeders;

use App\Models\System\Localization\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     * ISO 3166-1 國家清單（含英文名、當地語言名）
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        Country::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $countries = $this->getCountries();

        $this->command->info('開始匯入國家資料...');

        foreach ($countries as $index => $country) {
            Country::create([
                'name'              => $country[0],
                'native_name'       => $country[1],
                'iso_code_2'        => $country[2],
                'iso_code_3'        => $country[3],
                'address_format'    => null,
                'postcode_required' => false,
                'is_active'         => true,
                'sort_order'        => $index + 1,
            ]);
        }

        $this->command->info('匯入完成！總計 ' . count($countries) . ' 個國家');
    }

    /**
     * ISO 3166-1 國家清單
     * [name, native_name, iso_code_2, iso_code_3]
     */
    private function getCountries(): array
    {
        return [
            ['Afghanistan', 'افغانستان', 'AF', 'AFG'],
            ['Albania', 'Shqipëria', 'AL', 'ALB'],
            ['Algeria', 'الجزائر', 'DZ', 'DZA'],
            ['American Samoa', 'American Samoa', 'AS', 'ASM'],
            ['Andorra', 'Andorra', 'AD', 'AND'],
            ['Angola', 'Angola', 'AO', 'AGO'],
            ['Anguilla', 'Anguilla', 'AI', 'AIA'],
            ['Antarctica', 'Antarctica', 'AQ', 'ATA'],
            ['Antigua and Barbuda', 'Antigua and Barbuda', 'AG', 'ATG'],
            ['Argentina', 'Argentina', 'AR', 'ARG'],
            ['Armenia', 'Հայաստան', 'AM', 'ARM'],
            ['Aruba', 'Aruba', 'AW', 'ABW'],
            ['Australia', 'Australia', 'AU', 'AUS'],
            ['Austria', 'Österreich', 'AT', 'AUT'],
            ['Azerbaijan', 'Azərbaycan', 'AZ', 'AZE'],
            ['Bahamas', 'Bahamas', 'BS', 'BHS'],
            ['Bahrain', 'البحرين', 'BH', 'BHR'],
            ['Bangladesh', 'বাংলাদেশ', 'BD', 'BGD'],
            ['Barbados', 'Barbados', 'BB', 'BRB'],
            ['Belarus', 'Беларусь', 'BY', 'BLR'],
            ['Belgium', 'België', 'BE', 'BEL'],
            ['Belize', 'Belize', 'BZ', 'BLZ'],
            ['Benin', 'Bénin', 'BJ', 'BEN'],
            ['Bermuda', 'Bermuda', 'BM', 'BMU'],
            ['Bhutan', 'འབྲུག', 'BT', 'BTN'],
            ['Bolivia', 'Bolivia', 'BO', 'BOL'],
            ['Bosnia and Herzegovina', 'Bosna i Hercegovina', 'BA', 'BIH'],
            ['Botswana', 'Botswana', 'BW', 'BWA'],
            ['Bouvet Island', 'Bouvetøya', 'BV', 'BVT'],
            ['Brazil', 'Brasil', 'BR', 'BRA'],
            ['British Indian Ocean Territory', 'British Indian Ocean Territory', 'IO', 'IOT'],
            ['Brunei', 'Brunei', 'BN', 'BRN'],
            ['Bulgaria', 'България', 'BG', 'BGR'],
            ['Burkina Faso', 'Burkina Faso', 'BF', 'BFA'],
            ['Burundi', 'Burundi', 'BI', 'BDI'],
            ['Cambodia', 'កម្ពុជា', 'KH', 'KHM'],
            ['Cameroon', 'Cameroun', 'CM', 'CMR'],
            ['Canada', 'Canada', 'CA', 'CAN'],
            ['Cape Verde', 'Cabo Verde', 'CV', 'CPV'],
            ['Cayman Islands', 'Cayman Islands', 'KY', 'CYM'],
            ['Central African Republic', 'République centrafricaine', 'CF', 'CAF'],
            ['Chad', 'Tchad', 'TD', 'TCD'],
            ['Chile', 'Chile', 'CL', 'CHL'],
            ['China', '中国', 'CN', 'CHN'],
            ['Christmas Island', 'Christmas Island', 'CX', 'CXR'],
            ['Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'CC', 'CCK'],
            ['Colombia', 'Colombia', 'CO', 'COL'],
            ['Comoros', 'Komori', 'KM', 'COM'],
            ['Congo', 'Congo', 'CG', 'COG'],
            ['Congo, Democratic Republic', 'République démocratique du Congo', 'CD', 'COD'],
            ['Cook Islands', 'Cook Islands', 'CK', 'COK'],
            ['Costa Rica', 'Costa Rica', 'CR', 'CRI'],
            ['Croatia', 'Hrvatska', 'HR', 'HRV'],
            ['Cuba', 'Cuba', 'CU', 'CUB'],
            ['Curaçao', 'Curaçao', 'CW', 'CUW'],
            ['Cyprus', 'Κύπρος', 'CY', 'CYP'],
            ['Czech Republic', 'Česká republika', 'CZ', 'CZE'],
            ['Denmark', 'Danmark', 'DK', 'DNK'],
            ['Djibouti', 'Djibouti', 'DJ', 'DJI'],
            ['Dominica', 'Dominica', 'DM', 'DMA'],
            ['Dominican Republic', 'República Dominicana', 'DO', 'DOM'],
            ['Ecuador', 'Ecuador', 'EC', 'ECU'],
            ['Egypt', 'مصر', 'EG', 'EGY'],
            ['El Salvador', 'El Salvador', 'SV', 'SLV'],
            ['Equatorial Guinea', 'Guinea Ecuatorial', 'GQ', 'GNQ'],
            ['Eritrea', 'ኤርትራ', 'ER', 'ERI'],
            ['Estonia', 'Eesti', 'EE', 'EST'],
            ['Eswatini', 'Eswatini', 'SZ', 'SWZ'],
            ['Ethiopia', 'ኢትዮጵያ', 'ET', 'ETH'],
            ['Falkland Islands', 'Falkland Islands', 'FK', 'FLK'],
            ['Faroe Islands', 'Føroyar', 'FO', 'FRO'],
            ['Fiji', 'Fiji', 'FJ', 'FJI'],
            ['Finland', 'Suomi', 'FI', 'FIN'],
            ['France', 'France', 'FR', 'FRA'],
            ['French Guiana', 'Guyane française', 'GF', 'GUF'],
            ['French Polynesia', 'Polynésie française', 'PF', 'PYF'],
            ['French Southern Territories', 'Terres australes françaises', 'TF', 'ATF'],
            ['Gabon', 'Gabon', 'GA', 'GAB'],
            ['Gambia', 'Gambia', 'GM', 'GMB'],
            ['Georgia', 'საქართველო', 'GE', 'GEO'],
            ['Germany', 'Deutschland', 'DE', 'DEU'],
            ['Ghana', 'Ghana', 'GH', 'GHA'],
            ['Gibraltar', 'Gibraltar', 'GI', 'GIB'],
            ['Greece', 'Ελλάδα', 'GR', 'GRC'],
            ['Greenland', 'Kalaallit Nunaat', 'GL', 'GRL'],
            ['Grenada', 'Grenada', 'GD', 'GRD'],
            ['Guadeloupe', 'Guadeloupe', 'GP', 'GLP'],
            ['Guam', 'Guam', 'GU', 'GUM'],
            ['Guatemala', 'Guatemala', 'GT', 'GTM'],
            ['Guernsey', 'Guernsey', 'GG', 'GGY'],
            ['Guinea', 'Guinée', 'GN', 'GIN'],
            ['Guinea-Bissau', 'Guiné-Bissau', 'GW', 'GNB'],
            ['Guyana', 'Guyana', 'GY', 'GUY'],
            ['Haiti', 'Haïti', 'HT', 'HTI'],
            ['Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'HM', 'HMD'],
            ['Honduras', 'Honduras', 'HN', 'HND'],
            ['Hong Kong', '香港', 'HK', 'HKG'],
            ['Hungary', 'Magyarország', 'HU', 'HUN'],
            ['Iceland', 'Ísland', 'IS', 'ISL'],
            ['India', 'भारत', 'IN', 'IND'],
            ['Indonesia', 'Indonesia', 'ID', 'IDN'],
            ['Iran', 'ایران', 'IR', 'IRN'],
            ['Iraq', 'العراق', 'IQ', 'IRQ'],
            ['Ireland', 'Éire', 'IE', 'IRL'],
            ['Isle of Man', 'Isle of Man', 'IM', 'IMN'],
            ['Israel', 'ישראל', 'IL', 'ISR'],
            ['Italy', 'Italia', 'IT', 'ITA'],
            ['Ivory Coast', "Côte d'Ivoire", 'CI', 'CIV'],
            ['Jamaica', 'Jamaica', 'JM', 'JAM'],
            ['Japan', '日本', 'JP', 'JPN'],
            ['Jersey', 'Jersey', 'JE', 'JEY'],
            ['Jordan', 'الأردن', 'JO', 'JOR'],
            ['Kazakhstan', 'Қазақстан', 'KZ', 'KAZ'],
            ['Kenya', 'Kenya', 'KE', 'KEN'],
            ['Kiribati', 'Kiribati', 'KI', 'KIR'],
            ['Korea, North', '조선', 'KP', 'PRK'],
            ['Korea, South', '대한민국', 'KR', 'KOR'],
            ['Kuwait', 'الكويت', 'KW', 'KWT'],
            ['Kyrgyzstan', 'Кыргызстан', 'KG', 'KGZ'],
            ['Laos', 'ລາວ', 'LA', 'LAO'],
            ['Latvia', 'Latvija', 'LV', 'LVA'],
            ['Lebanon', 'لبنان', 'LB', 'LBN'],
            ['Lesotho', 'Lesotho', 'LS', 'LSO'],
            ['Liberia', 'Liberia', 'LR', 'LBR'],
            ['Libya', 'ليبيا', 'LY', 'LBY'],
            ['Liechtenstein', 'Liechtenstein', 'LI', 'LIE'],
            ['Lithuania', 'Lietuva', 'LT', 'LTU'],
            ['Luxembourg', 'Luxembourg', 'LU', 'LUX'],
            ['Macao', '澳門', 'MO', 'MAC'],
            ['Madagascar', 'Madagasikara', 'MG', 'MDG'],
            ['Malawi', 'Malawi', 'MW', 'MWI'],
            ['Malaysia', 'Malaysia', 'MY', 'MYS'],
            ['Maldives', 'Maldives', 'MV', 'MDV'],
            ['Mali', 'Mali', 'ML', 'MLI'],
            ['Malta', 'Malta', 'MT', 'MLT'],
            ['Marshall Islands', 'Marshall Islands', 'MH', 'MHL'],
            ['Martinique', 'Martinique', 'MQ', 'MTQ'],
            ['Mauritania', 'موريتانيا', 'MR', 'MRT'],
            ['Mauritius', 'Maurice', 'MU', 'MUS'],
            ['Mayotte', 'Mayotte', 'YT', 'MYT'],
            ['Mexico', 'México', 'MX', 'MEX'],
            ['Micronesia', 'Micronesia', 'FM', 'FSM'],
            ['Moldova', 'Moldova', 'MD', 'MDA'],
            ['Monaco', 'Monaco', 'MC', 'MCO'],
            ['Mongolia', 'Монгол', 'MN', 'MNG'],
            ['Montenegro', 'Crna Gora', 'ME', 'MNE'],
            ['Montserrat', 'Montserrat', 'MS', 'MSR'],
            ['Morocco', 'المغرب', 'MA', 'MAR'],
            ['Mozambique', 'Moçambique', 'MZ', 'MOZ'],
            ['Myanmar', 'မြန်မာ', 'MM', 'MMR'],
            ['Namibia', 'Namibia', 'NA', 'NAM'],
            ['Nauru', 'Nauru', 'NR', 'NRU'],
            ['Nepal', 'नेपाल', 'NP', 'NPL'],
            ['Netherlands', 'Nederland', 'NL', 'NLD'],
            ['New Caledonia', 'Nouvelle-Calédonie', 'NC', 'NCL'],
            ['New Zealand', 'New Zealand', 'NZ', 'NZL'],
            ['Nicaragua', 'Nicaragua', 'NI', 'NIC'],
            ['Niger', 'Niger', 'NE', 'NER'],
            ['Nigeria', 'Nigeria', 'NG', 'NGA'],
            ['Niue', 'Niue', 'NU', 'NIU'],
            ['Norfolk Island', 'Norfolk Island', 'NF', 'NFK'],
            ['North Macedonia', 'Северна Македонија', 'MK', 'MKD'],
            ['Northern Mariana Islands', 'Northern Mariana Islands', 'MP', 'MNP'],
            ['Norway', 'Norge', 'NO', 'NOR'],
            ['Oman', 'عمان', 'OM', 'OMN'],
            ['Pakistan', 'پاکستان', 'PK', 'PAK'],
            ['Palau', 'Palau', 'PW', 'PLW'],
            ['Palestine', 'فلسطين', 'PS', 'PSE'],
            ['Panama', 'Panamá', 'PA', 'PAN'],
            ['Papua New Guinea', 'Papua New Guinea', 'PG', 'PNG'],
            ['Paraguay', 'Paraguay', 'PY', 'PRY'],
            ['Peru', 'Perú', 'PE', 'PER'],
            ['Philippines', 'Pilipinas', 'PH', 'PHL'],
            ['Pitcairn', 'Pitcairn', 'PN', 'PCN'],
            ['Poland', 'Polska', 'PL', 'POL'],
            ['Portugal', 'Portugal', 'PT', 'PRT'],
            ['Puerto Rico', 'Puerto Rico', 'PR', 'PRI'],
            ['Qatar', 'قطر', 'QA', 'QAT'],
            ['Réunion', 'La Réunion', 'RE', 'REU'],
            ['Romania', 'România', 'RO', 'ROU'],
            ['Russia', 'Россия', 'RU', 'RUS'],
            ['Rwanda', 'Rwanda', 'RW', 'RWA'],
            ['Saint Barthélemy', 'Saint-Barthélemy', 'BL', 'BLM'],
            ['Saint Helena', 'Saint Helena', 'SH', 'SHN'],
            ['Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'KN', 'KNA'],
            ['Saint Lucia', 'Saint Lucia', 'LC', 'LCA'],
            ['Saint Martin', 'Saint-Martin', 'MF', 'MAF'],
            ['Saint Pierre and Miquelon', 'Saint-Pierre-et-Miquelon', 'PM', 'SPM'],
            ['Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VC', 'VCT'],
            ['Samoa', 'Samoa', 'WS', 'WSM'],
            ['San Marino', 'San Marino', 'SM', 'SMR'],
            ['Sao Tome and Principe', 'São Tomé e Príncipe', 'ST', 'STP'],
            ['Saudi Arabia', 'السعودية', 'SA', 'SAU'],
            ['Senegal', 'Sénégal', 'SN', 'SEN'],
            ['Serbia', 'Србија', 'RS', 'SRB'],
            ['Seychelles', 'Seychelles', 'SC', 'SYC'],
            ['Sierra Leone', 'Sierra Leone', 'SL', 'SLE'],
            ['Singapore', 'Singapore', 'SG', 'SGP'],
            ['Sint Maarten', 'Sint Maarten', 'SX', 'SXM'],
            ['Slovakia', 'Slovensko', 'SK', 'SVK'],
            ['Slovenia', 'Slovenija', 'SI', 'SVN'],
            ['Solomon Islands', 'Solomon Islands', 'SB', 'SLB'],
            ['Somalia', 'Soomaaliya', 'SO', 'SOM'],
            ['South Africa', 'South Africa', 'ZA', 'ZAF'],
            ['South Georgia', 'South Georgia', 'GS', 'SGS'],
            ['South Sudan', 'South Sudan', 'SS', 'SSD'],
            ['Spain', 'España', 'ES', 'ESP'],
            ['Sri Lanka', 'ශ්‍රී ලංකාව', 'LK', 'LKA'],
            ['Sudan', 'السودان', 'SD', 'SDN'],
            ['Suriname', 'Suriname', 'SR', 'SUR'],
            ['Svalbard and Jan Mayen', 'Svalbard og Jan Mayen', 'SJ', 'SJM'],
            ['Sweden', 'Sverige', 'SE', 'SWE'],
            ['Switzerland', 'Schweiz', 'CH', 'CHE'],
            ['Syria', 'سوريا', 'SY', 'SYR'],
            ['Taiwan', '臺灣', 'TW', 'TWN'],
            ['Tajikistan', 'Тоҷикистон', 'TJ', 'TJK'],
            ['Tanzania', 'Tanzania', 'TZ', 'TZA'],
            ['Thailand', 'ประเทศไทย', 'TH', 'THA'],
            ['Timor-Leste', 'Timor-Leste', 'TL', 'TLS'],
            ['Togo', 'Togo', 'TG', 'TGO'],
            ['Tokelau', 'Tokelau', 'TK', 'TKL'],
            ['Tonga', 'Tonga', 'TO', 'TON'],
            ['Trinidad and Tobago', 'Trinidad and Tobago', 'TT', 'TTO'],
            ['Tunisia', 'تونس', 'TN', 'TUN'],
            ['Turkey', 'Türkiye', 'TR', 'TUR'],
            ['Turkmenistan', 'Türkmenistan', 'TM', 'TKM'],
            ['Turks and Caicos Islands', 'Turks and Caicos Islands', 'TC', 'TCA'],
            ['Tuvalu', 'Tuvalu', 'TV', 'TUV'],
            ['Uganda', 'Uganda', 'UG', 'UGA'],
            ['Ukraine', 'Україна', 'UA', 'UKR'],
            ['United Arab Emirates', 'الإمارات', 'AE', 'ARE'],
            ['United Kingdom', 'United Kingdom', 'GB', 'GBR'],
            ['United States', 'United States', 'US', 'USA'],
            ['United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'UM', 'UMI'],
            ['Uruguay', 'Uruguay', 'UY', 'URY'],
            ['Uzbekistan', 'Oʻzbekiston', 'UZ', 'UZB'],
            ['Vanuatu', 'Vanuatu', 'VU', 'VUT'],
            ['Vatican City', 'Città del Vaticano', 'VA', 'VAT'],
            ['Venezuela', 'Venezuela', 'VE', 'VEN'],
            ['Vietnam', 'Việt Nam', 'VN', 'VNM'],
            ['Virgin Islands, British', 'British Virgin Islands', 'VG', 'VGB'],
            ['Virgin Islands, U.S.', 'U.S. Virgin Islands', 'VI', 'VIR'],
            ['Wallis and Futuna', 'Wallis-et-Futuna', 'WF', 'WLF'],
            ['Western Sahara', 'الصحراء الغربية', 'EH', 'ESH'],
            ['Yemen', 'اليمن', 'YE', 'YEM'],
            ['Zambia', 'Zambia', 'ZM', 'ZMB'],
            ['Zimbabwe', 'Zimbabwe', 'ZW', 'ZWE'],
        ];
    }
}
